name: Update helm charts
on:
  workflow_call:
  workflow_dispatch:
jobs:
  update-sbomscanner-charts:
    name: Update SBOMscanner charts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests:  read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@9c04c99c508b3ac7851020724a912adde546f64b # v2.95.0

      # Helm and helm plugins installation required by the updatecli release action
      - name: Install helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - name: Install helm values schema json plugin
        run: helm plugin install https://github.com/losisin/helm-values-schema-json.git

      - name: Update SBOMscanner charts
        env:
          UPDATECLI_GITHUB_APP_CLIENT_ID: ${{ secrets.APP_ID }}
          UPDATECLI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          UPDATECLI_GITHUB_APP_INSTALLATION_ID: "${{ secrets.APP_INSTALLATION_ID }}"
        run: "updatecli compose apply --file updatecli/updatecli-compose.release.yaml"
